In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from warnings import filterwarnings
filterwarnings('ignore')

### connected colab Gpu in vs code

In [2]:
import torch
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

GPU Available: False

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB

In [7]:
df.drop(['deck', 'embark_town', 'alive','class','who','adult_male'], axis=1, inplace=True)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    str
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 61.8 KB

In [9]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'] = df['age'].fillna(df['age'].mean())

In [10]:
df.dropna(subset=['embarked'], inplace=True)

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    str
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 68.5 KB

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [14]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [15]:
df.astype('float32')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0.0,3.0,1.0,22.000000,1.0,0.0,7.250000,2.0,0.0
1,1.0,1.0,0.0,38.000000,1.0,0.0,71.283302,0.0,0.0
2,1.0,3.0,0.0,26.000000,0.0,0.0,7.925000,2.0,1.0
3,1.0,1.0,0.0,35.000000,1.0,0.0,53.099998,2.0,0.0
4,0.0,3.0,1.0,35.000000,0.0,0.0,8.050000,2.0,1.0
...,...,...,...,...,...,...,...,...,...
886,0.0,2.0,1.0,27.000000,0.0,0.0,13.000000,2.0,1.0
887,1.0,1.0,0.0,19.000000,0.0,0.0,30.000000,2.0,1.0
888,0.0,3.0,0.0,29.699118,1.0,2.0,23.450001,2.0,0.0
889,1.0,1.0,1.0,26.000000,0.0,0.0,30.000000,0.0,1.0
890,0.0,3.0,1.0,32.000000,0.0,0.0,7.750000,1.0,1.0

In [16]:
x = df.drop('survived', axis=1)
y = df['survived']

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train, y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(x_test)

In [21]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [22]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [26]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [27]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [30]:
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [31]:
x_train

     pclass  sex        age  sibsp  parch      fare  embarked  alone
708       1    0  22.000000      0      0  151.5500         2   True
240       3    0  29.699118      1      0   14.4542         0  False
382       3    1  32.000000      0      0    7.9250         2   True
792       3    0  29.699118      8      2   69.5500         2  False
683       3    1  14.000000      5      2   46.9000         2  False
..      ...  ...        ...    ...    ...       ...       ...    ...
107       3    1  29.699118      0      0    7.7750         2   True
271       3    1  25.000000      0      0    0.0000         2   True
862       1    0  48.000000      0      0   25.9292         2   True
436       3    0  21.000000      2      2   34.3750         2  False
103       3    1  33.000000      0      0    8.6542         2   True

[711 rows x 8 columns]

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [33]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [35]:
x_train_scaled, x_test_scaled

(array([[-1.58410418, -1.40530972, -0.59963554, ...,  2.43059683,
          0.58770431,  0.81076671],
        [ 0.8122747 , -1.40530972, -0.01249955, ..., -0.35813533,
         -1.95246446, -1.23340042],
        [ 0.8122747 ,  0.71158691,  0.16296612, ..., -0.49094895,
          0.58770431,  0.81076671],
        ...,
        [-1.58410418, -1.40530972,  1.38312878, ..., -0.12471679,
          0.58770431,  0.81076671],
        [ 0.8122747 , -1.40530972, -0.67589571, ...,  0.04708333,
          0.58770431, -1.23340042],
        [ 0.8122747 ,  0.71158691,  0.23922629, ..., -0.47611594,
          0.58770431,  0.81076671]], shape=(711, 8)),
 array([[ 0.8122747 ,  0.71158691, -0.14207455, ..., -0.49238913,
          0.58770431,  0.81076671],
        [-1.58410418, -1.40530972, -1.20971688, ...,  1.78882298,
          0.58770431, -1.23340042],
        [ 0.8122747 , -1.40530972, -1.20971688, ..., -0.42348235,
         -1.95246446, -1.23340042],
        ...,
        [ 0.8122747 , -1.40530972,  0.62052712, ..., -0.01368686,
          0.58770431, -1.23340042],
        [ 0.8122747 , -1.40530972,  0.23922629, ..., -0.32974268,
          0.58770431, -1.23340042],
        [ 0.8122747 , -1.40530972, -1.97231854, ..., -0.31245242,
          0.58770431, -1.23340042]], shape=(178, 8)))

In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [38]:
knn.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [39]:
y_pred_knn = knn.predict(x_test_scaled)

In [40]:
accuracy_score(y_test, y_pred_knn)

0.797752808988764

In [41]:
confusion_matrix(y_test,y_pred_knn)

array([[90, 19],
       [17, 52]])

In [42]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [1]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
x = df.drop('survived', axis=1)
y = df['survived']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model_NB = GaussianNB()
model_NB.fit(x_train, y_train)